spring:
  data:
    mongodb:
      uri: mongodb://paypo:paypo@localhost:27017/scoring?retryWrites=false&authSource=admin&ssl=false
  config:
    import: optional:file:.environment-variables[.properties]

accuweather:
  apikey: ${ACCU_WEATHER_API_KEY}
  url: ${ACCU_WEATHER_URL}

logging:
  level:
    com.witek.weatherapi: DEBUG
    org.zalando.logbook: TRACE
